[build]
  command = "npm run build"
  publish = "src/web/dist"
  functions = "netlify/functions"

[build.environment]
  # Le variabili d'ambiente vengono configurate nel dashboard Netlify
  # VITE_SUPABASE_URL = "https://your-project.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "your-anon-key"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200